# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diablo_4_loot_filter.proto
# Protobuf Python Version: 7.35.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '-rc1',
    'diablo_4_loot_filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64iablo_4_loot_filter.proto\x12\nlootfilter\"]\n\nLootFilter\x12\x1f\n\x05rules\x18\x01 \x03(\x0b\x32\x10.lootfilter.Rule\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x66ield_3\x18\x03 \x01(\r\x12\x0f\n\x07\x66ield_4\x18\x04 \x01(\r\"\x8c\x01\n\x04Rule\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32\x16.lootfilter.RuleAction\x12\r\n\x05\x63olor\x18\x03 \x01(\x07\x12)\n\nconditions\x18\x04 \x03(\x0b\x32\x15.lootfilter.Condition\x12\x0f\n\x07\x65nabled\x18\x05 \x01(\x08\"\xb2\x01\n\tCondition\x12\x31\n\x0e\x63ondition_type\x18\x01 \x01(\x0e\x32\x19.lootfilter.ConditionType\x12\x0e\n\x06values\x18\x02 \x03(\x07\x12-\n\x0especial_values\x18\x03 \x03(\x0b\x32\x15.lootfilter.PairRange\x12\x11\n\tthreshold\x18\x04 \x01(\r\x12\x0f\n\x07\x66ield_5\x18\x05 \x01(\r\x12\x0f\n\x07\x66ield_6\x18\x06 \x01(\r\"-\n\tPairRange\x12\x0f\n\x07value_1\x18\x01 \x01(\x07\x12\x0f\n\x07value_2\x18\x02 \x01(\x07*L\n\nRuleAction\x12\r\n\tSHOW_ITEM\x10\x00\x12\x13\n\x0fHIDE_TEXT_LABEL\x10\x01\x12\x0b\n\x07RECOLOR\x10\x02\x12\r\n\tHIDE_ITEM\x10\x03*\x86\x01\n\rConditionType\x12\x15\n\x11\x43ONDITION_UNKNOWN\x10\x00\x12\x1b\n\x17\x43ONDITION_CODEX_UPGRADE\x10\x03\x12!\n\x1d\x43ONDITION_GREATER_AFFIX_COUNT\x10\x04\x12\x1e\n\x1a\x43ONDITION_REQUIRED_AFFIXES\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diablo_4_loot_filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULEACTION']._serialized_start=508
  _globals['_RULEACTION']._serialized_end=584
  _globals['_CONDITIONTYPE']._serialized_start=587
  _globals['_CONDITIONTYPE']._serialized_end=721
  _globals['_LOOTFILTER']._serialized_start=42
  _globals['_LOOTFILTER']._serialized_end=135
  _globals['_RULE']._serialized_start=138
  _globals['_RULE']._serialized_end=278
  _globals['_CONDITION']._serialized_start=281
  _globals['_CONDITION']._serialized_end=459
  _globals['_PAIRRANGE']._serialized_start=461
  _globals['_PAIRRANGE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
