import base64


b64 = "ChgKB015dGhpY3MQAh3VIQj/IgQIASAgKAEKFgoDR0FzEAIdygD//yIGCAQgATABKAEKHgoNY29kZXggdXBncmFkZRACHQAA//8iBAgDMAEoAQoVCgRTZXRzEAId/v8A/yIECAEgQCgBCjAKB1VuaXF1ZXMQAh3+/wD/IhYICBWI5xMAFeVLGwAVnroWABW/lgQAIgQIASAQKAEKLAoNQ2hhcm0gJiBTZWFscxACHf7/AP8iBAgBIHgiDAgFFQXtIgAVgH4jACgBChMKCGhpZGUgYWxsEAMdAAD//ygBEhVSb2JzIFdXIEJhcmIgLSBTVFJJQ1QYAiAC"
data = base64.b64decode(b64)

with open("data.bin", "wb") as f:
    f.write(data)

print(data)